version: "3.9"
services:
  backend:
    build: ./backend
    container_name: stock_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./dataset:/app/dataset
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///./stock_data.db
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: stock_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: stock_db
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
      POSTGRES_DB: stockdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
